import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Banner from '../components/Banner'
import Footer from '../components/Footer'
import CategoryIcons from '../components/CategoryIcons'
import SectionSlider from '../components/SectionSlider'
import ProductFeed from '../components/ProductFeed'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import GridSectionSlider from '../components/GridSectionSlider'
import { GRAPHQL_URL } from '../lib/constants'

export default function Home({products}) {
  const router = useRouter()
  // const [loading, setLoading] = useState(false)
    useEffect(() => {
    // let token = sessionStorage.getItem("Token");
    // if (!token) {
    //   router.push("/login");
    // }
    // setTimeout(() => {
    //   setLoading(true);
    // }, 500)
  }, );
  return (
    <div>
      <Head>
        <title>Aerosmart Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <main>
      <Header/>
      {/* {loading ? */}
      <>
     <Banner/>
     <CategoryIcons/>
     <SectionSlider sectionTitle={'latest products'} products={products}/>
     <GridSectionSlider sectionTitle={'top selling products'} products={products} />
     <div className="px-2 mt-7 mb-3">
     <div className="uppercase bg-gray-300 p-2 text-gray-700 rounded-md">
      <h2 className="text-center ">
        Products
      </h2>
     </div>
     </div>
     <ProductFeed/>
     <Footer />
      </>
      {/* : */}
          {/* <p className='my-2'>Loading</p>
} */}
     </main>
    </div>

  )
}


export const getServerSideProps = async (context) => {
  const page = 1
  const graphqlQuery = {
    query: `
    {
      products(page: ${page}) {
        products{
          id
          title
          price
          imageUrl
          description
        }
      }
    }
    `
  };
   const result = await fetch(process.env.NEXT_PUBLIC_GRAPHQL_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(graphqlQuery)
    })
      .then(res => {  
        return res.json();
      })
      .then(resData => {
        return resData
      })
      .catch(err => console.log(err))
     
      const data = await result
    return {
      props: {
        products: data?.data?.products?.products || []
      }
    }
  }
