import { app } from "../firebase";
import { useRouter } from "next/router";
import {
  getAuth,
  signInWithPopup,
  GoogleAuthProvider,
  signInWithEmailAndPassword,
} from "firebase/auth";
import Link from "next/link";
import { useEffect, useState } from "react";
import { FcGoogle } from "react-icons/fc";
import Head from "next/head";
import { RiFacebookFill } from "react-icons/ri";

function Login() {
  const auth = getAuth(app);
  const googleProvider = new GoogleAuthProvider();
  const router = useRouter();
  const signInGoogle = async () => {
    signInWithPopup(auth, googleProvider)
      .then((response) => {
        router.push("/");
        sessionStorage.setItem("Token", response.user.accessToken);
      })
      .catch((err) => console.log(err));
  };
  const signIn = async () => {};
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const emailInputHandler = (e) => {
    const content = e.target.value;
    setEmail(content);
  };
  const passwordInputHandler = (e) => {
    const content = e.target.value;
    setPassword(content);
  };
  const emailIsValid = email.includes("@");
  const passwordIsValid = password.length >= 6;

  const loginHandler = async (e) => {
    e.preventDefault();
    if (emailIsValid && passwordIsValid) {
      signInWithEmailAndPassword(auth, email, password)
        .then((response) => {
          console.log(response.user);
          sessionStorage.setItem("Token", response.user.accessToken);
          router.push("/");
        })
        .catch((err) => {
          console.log(err);
        });
    }
  };
  // useEffect(() => {
  //   let token = sessionStorage.getItem("Token");
  //   if (token) {
  //     router.push("/");
  //   }
  // }, []);

  return (
<div className="my-10 grid grid-cols-1 place-content-center overflow-y-scroll">
       <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* fonts import */}
        <link rel='preconnect' href='https://fonts.googleapis.com' />
          <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin="true" />
          <link href='https://fonts.googleapis.com/css2?family=Calligraffitti&family=Changa:wght@200;300;400;500;600;700;800&family=Edu+VIC+WA+NT+Beginner:wght@400;500;600;700&family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Cairo:wght@200;300;400;500;600;700;800;900;1000&family=Exo+2:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,600;1,700;1,800&family=Lobster+Two:ital,wght@0,400;0,700;1,400;1,700&family=Play:wght@400;700&family=Rajdhani:wght@300;400;500;600;700&family=Titillium+Web:ital,wght@0,200;0,300;0,400;0,600;0,700;1,200;1,300;1,400;1,600;1,700&family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800&family=Metal+Mania&family=Montez&family=Montserrat+Alternates:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Play:wght@400;700&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,400;1,500;1,700;1,900&family=Sedgwick+Ave+Display&display=swap&family=PT+Serif:ital@0;1&display=swap'
            rel='stylesheet'
          />

      </Head>
      {/* <div className='px-2 flex justify-center  md:px-4 lg:px-0  items-center h-screen '>
        <div className='border-2  border-[#093158]  px-2 lg:px-8 py-8 rounded-lg lg:rounded-xl bg-white shadow-xl drop-shadow-2xl   text-[#093158] w-[95%] md:w-[80%] md:mb-20 lg:w-[600px] 2xl:w-[700px] '>
          <h1 className='text-center  text-5xl '>
            LOG<span className='text-[#ffcb05]'>IN</span>
          </h1>
          <div className='m-auto flex w-[100px] h-[2px] bg-[#ffcb05]'></div>
          <form onSubmit={loginHandler}>
            <input
              type='text'
              className='border-[2px] lg:border-[1px] rounded-lg md:rounded-full  border-[#093158] outline-none px-6 py-3 w-[90%]  m-auto flex my-10 lg:my-8'
              placeholder='Email'
              required
              onChange={emailInputHandler}
            />
            <input
              type='password'
              className='border-[2px] lg:border-[1px] rounded-lg md:rounded-full  border-[#093158] outline-none px-6 py-3 w-[90%]  m-auto flex my-10 lg:my-8'
              placeholder='Password'
              required
              onChange={passwordInputHandler}
            />

            <button className='flex justify-center m-auto mt-5 lg:mt-5  bg-[#093158] w-56 rounded-full text-white  px-2 py-3 2xl:p-3 outline-none transition-all duration-300 ease-in-out hover:bg-[#ffcb05] 2xl:w-[300px]'>
              LOGIN
            </button>
          </form>
          <div className='flex justify-center mt-3 space-x-4'>
            <Link href='/forgot-password'>
              <p>forgot password? </p>
            </Link>
            <Link href='/signup'>
              <p className='text-[#ffcb05] hover:text-blue-500 transition-colors duration-200 ease-linear'>
                Signup
              </p>
            </Link>
          </div>
          <button
            className='flex justify-center m-auto mt-2  bg-transparent text-[#093158] w-56 rounded-full border-[2px]  px-2 py-3 2xl:p-3 outline-none transition-all duration-200 ease-in hover:bg-[#093158] hover:text-white 2xl:w-[300px] items-center'
            onClick={signInGoogle}
          >
            <FcGoogle className='h-5' /> {""}
            <p> SIGN IN WITH GOOGLE</p>
          </button>
        </div>
      </div> */}

      
<h2 className="sm:mt-24 text-2xl text-center font-bold mb-2  ">Login</h2>
      <h2 className="text-2xl text-center font-bold mb-2">Welcome Back</h2>
      <form onSubmit={loginHandler}>
      <input
              type='email'
              className='border-[1px] lg:border-[1px] rounded-lg md:rounded-full  border-gray-500] outline-none px-6 py-[16px] w-[90%]  m-auto flex my-5 lg:my-5'
              placeholder='Enter email '
              required
              onChange={passwordInputHandler}
            />
      <input
              type='password'
              className='border-[1px] lg:border-[1px] rounded-lg md:rounded-full  border-gray-500] outline-none px-6 py-[16px] w-[90%]  m-auto flex my-5 lg:my-5'
              placeholder='Password'
              required
              onChange={passwordInputHandler}
            />
        </form>

        <Link href="/forgot-password">
         <p  className="text-[#2F89FC] capitalize text-center font-poppins">forgot password?</p>
        </Link>

        <button className="capitalize w-[90%] h-[48px] rounded-md text-white bg-[#0E64D2] block mt-4 m-auto">login</button>

        <p className="font-poppins text-center mt-4">Dont have an account?
        <Link href="/signup" className="font-poppins text-[#2F89FC] ml-4">Signup</Link>
        </p>

        <div className="flex items-center justify-between px-4 mt-4">
          <span className="w-[44%] h-[1px] bg-gray-700"></span>
          <p className="font-poppins  text-lg">or</p>
          <span className="w-[44%] h-[1px] bg-gray-700"></span>
        </div>

        <button className=" w-[90%] h-[48px] rounded-md text-white bg-[#1877F2]  mt-4 m-auto flex items-center justify-between px-2">
        <RiFacebookFill className="w-7 h-7 "/>
          Login with Facebook
          <div></div>
          </button>

        <button className=" w-[90%] h-[48px] rounded-md text-gray-500 border-[1px] bg-white mt-4 m-auto flex items-center justify-between px-2 mb-4 sm:mb-0"   onClick={signInGoogle}>
        <FcGoogle className="w-7 h-7 "/>
          Login with Google
          <div></div>
          </button>

      </div>
  );
}

export default Login;

Login.getLayout = function pageLayout(page) {
  return <>{page}</>;
};
